/*
 * This file is generated by jOOQ.
*/
package com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = -387220905;

    private Integer id;
    private String  fullName;
    private String  authId;
    private byte[]  encryptedPassword;
    private Integer passwordEncryptionTypeId;

    public Users() {}

    public Users(Users value) {
        this.id = value.id;
        this.fullName = value.fullName;
        this.authId = value.authId;
        this.encryptedPassword = value.encryptedPassword;
        this.passwordEncryptionTypeId = value.passwordEncryptionTypeId;
    }

    public Users(
        Integer id,
        String  fullName,
        String  authId,
        byte[]  encryptedPassword,
        Integer passwordEncryptionTypeId
    ) {
        this.id = id;
        this.fullName = fullName;
        this.authId = authId;
        this.encryptedPassword = encryptedPassword;
        this.passwordEncryptionTypeId = passwordEncryptionTypeId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getFullName() {
        return this.fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getAuthId() {
        return this.authId;
    }

    public void setAuthId(String authId) {
        this.authId = authId;
    }

    public byte[] getEncryptedPassword() {
        return this.encryptedPassword;
    }

    public void setEncryptedPassword(byte... encryptedPassword) {
        this.encryptedPassword = encryptedPassword;
    }

    public Integer getPasswordEncryptionTypeId() {
        return this.passwordEncryptionTypeId;
    }

    public void setPasswordEncryptionTypeId(Integer passwordEncryptionTypeId) {
        this.passwordEncryptionTypeId = passwordEncryptionTypeId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(id);
        sb.append(", ").append(fullName);
        sb.append(", ").append(authId);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(passwordEncryptionTypeId);

        sb.append(")");
        return sb.toString();
    }
}
