/*
 * This file is generated by jOOQ.
*/
package com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserPasswordEncryptionTypes implements Serializable {

    private static final long serialVersionUID = -1487541200;

    private Integer   id;
    private String    typeName;
    private byte[]    secretKey;
    private String    description;
    private String    url;
    private Timestamp createdAt;
    private Timestamp deletedAt;

    public UserPasswordEncryptionTypes() {}

    public UserPasswordEncryptionTypes(UserPasswordEncryptionTypes value) {
        this.id = value.id;
        this.typeName = value.typeName;
        this.secretKey = value.secretKey;
        this.description = value.description;
        this.url = value.url;
        this.createdAt = value.createdAt;
        this.deletedAt = value.deletedAt;
    }

    public UserPasswordEncryptionTypes(
        Integer   id,
        String    typeName,
        byte[]    secretKey,
        String    description,
        String    url,
        Timestamp createdAt,
        Timestamp deletedAt
    ) {
        this.id = id;
        this.typeName = typeName;
        this.secretKey = secretKey;
        this.description = description;
        this.url = url;
        this.createdAt = createdAt;
        this.deletedAt = deletedAt;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTypeName() {
        return this.typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public byte[] getSecretKey() {
        return this.secretKey;
    }

    public void setSecretKey(byte... secretKey) {
        this.secretKey = secretKey;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    public Timestamp getDeletedAt() {
        return this.deletedAt;
    }

    public void setDeletedAt(Timestamp deletedAt) {
        this.deletedAt = deletedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserPasswordEncryptionTypes (");

        sb.append(id);
        sb.append(", ").append(typeName);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(description);
        sb.append(", ").append(url);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(deletedAt);

        sb.append(")");
        return sb.toString();
    }
}
