/*
 * This file is generated by jOOQ.
*/
package com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserContactLogs implements Serializable {

    private static final long serialVersionUID = -792942561;

    private Integer   id;
    private Integer   infoId;
    private Timestamp issuedAt;
    private Integer   subjectId;
    private Timestamp contactedAt;
    private String    content;
    private Timestamp deletedAt;

    public UserContactLogs() {}

    public UserContactLogs(UserContactLogs value) {
        this.id = value.id;
        this.infoId = value.infoId;
        this.issuedAt = value.issuedAt;
        this.subjectId = value.subjectId;
        this.contactedAt = value.contactedAt;
        this.content = value.content;
        this.deletedAt = value.deletedAt;
    }

    public UserContactLogs(
        Integer   id,
        Integer   infoId,
        Timestamp issuedAt,
        Integer   subjectId,
        Timestamp contactedAt,
        String    content,
        Timestamp deletedAt
    ) {
        this.id = id;
        this.infoId = infoId;
        this.issuedAt = issuedAt;
        this.subjectId = subjectId;
        this.contactedAt = contactedAt;
        this.content = content;
        this.deletedAt = deletedAt;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getInfoId() {
        return this.infoId;
    }

    public void setInfoId(Integer infoId) {
        this.infoId = infoId;
    }

    public Timestamp getIssuedAt() {
        return this.issuedAt;
    }

    public void setIssuedAt(Timestamp issuedAt) {
        this.issuedAt = issuedAt;
    }

    public Integer getSubjectId() {
        return this.subjectId;
    }

    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    public Timestamp getContactedAt() {
        return this.contactedAt;
    }

    public void setContactedAt(Timestamp contactedAt) {
        this.contactedAt = contactedAt;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Timestamp getDeletedAt() {
        return this.deletedAt;
    }

    public void setDeletedAt(Timestamp deletedAt) {
        this.deletedAt = deletedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserContactLogs (");

        sb.append(id);
        sb.append(", ").append(infoId);
        sb.append(", ").append(issuedAt);
        sb.append(", ").append(subjectId);
        sb.append(", ").append(contactedAt);
        sb.append(", ").append(content);
        sb.append(", ").append(deletedAt);

        sb.append(")");
        return sb.toString();
    }
}
