/*
 * This file is generated by jOOQ.
*/
package com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserPasswordEncryptionTypes implements Serializable {

    private static final long serialVersionUID = -871664655;

    private Integer   id;
    private String    typeName;
    private byte[]    secretKey;
    private String    title;
    private Timestamp createdAt;
    private Timestamp deletedAt;

    public UserPasswordEncryptionTypes() {}

    public UserPasswordEncryptionTypes(UserPasswordEncryptionTypes value) {
        this.id = value.id;
        this.typeName = value.typeName;
        this.secretKey = value.secretKey;
        this.title = value.title;
        this.createdAt = value.createdAt;
        this.deletedAt = value.deletedAt;
    }

    public UserPasswordEncryptionTypes(
        Integer   id,
        String    typeName,
        byte[]    secretKey,
        String    title,
        Timestamp createdAt,
        Timestamp deletedAt
    ) {
        this.id = id;
        this.typeName = typeName;
        this.secretKey = secretKey;
        this.title = title;
        this.createdAt = createdAt;
        this.deletedAt = deletedAt;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTypeName() {
        return this.typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public byte[] getSecretKey() {
        return this.secretKey;
    }

    public void setSecretKey(byte... secretKey) {
        this.secretKey = secretKey;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    public Timestamp getDeletedAt() {
        return this.deletedAt;
    }

    public void setDeletedAt(Timestamp deletedAt) {
        this.deletedAt = deletedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserPasswordEncryptionTypes (");

        sb.append(id);
        sb.append(", ").append(typeName);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(title);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(deletedAt);

        sb.append(")");
        return sb.toString();
    }
}
