/*
 * This file is generated by jOOQ.
*/
package com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserPasswordHistories implements Serializable {

    private static final long serialVersionUID = -453898752;

    private Integer   id;
    private byte[]    encryptedPassword;
    private Integer   encryptionTypeId;
    private Integer   userId;
    private Timestamp createdAt;

    public UserPasswordHistories() {}

    public UserPasswordHistories(UserPasswordHistories value) {
        this.id = value.id;
        this.encryptedPassword = value.encryptedPassword;
        this.encryptionTypeId = value.encryptionTypeId;
        this.userId = value.userId;
        this.createdAt = value.createdAt;
    }

    public UserPasswordHistories(
        Integer   id,
        byte[]    encryptedPassword,
        Integer   encryptionTypeId,
        Integer   userId,
        Timestamp createdAt
    ) {
        this.id = id;
        this.encryptedPassword = encryptedPassword;
        this.encryptionTypeId = encryptionTypeId;
        this.userId = userId;
        this.createdAt = createdAt;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public byte[] getEncryptedPassword() {
        return this.encryptedPassword;
    }

    public void setEncryptedPassword(byte... encryptedPassword) {
        this.encryptedPassword = encryptedPassword;
    }

    public Integer getEncryptionTypeId() {
        return this.encryptionTypeId;
    }

    public void setEncryptionTypeId(Integer encryptionTypeId) {
        this.encryptionTypeId = encryptionTypeId;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserPasswordHistories (");

        sb.append(id);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(encryptionTypeId);
        sb.append(", ").append(userId);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
