/*
 * This file is generated by jOOQ.
*/
package com.anzoo_anzoom.database.information_schema.tables;


import com.anzoo_anzoom.database.information_schema.InformationSchema;
import com.anzoo_anzoom.database.information_schema.tables.records.InnodbCmpResetRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InnodbCmpReset extends TableImpl<InnodbCmpResetRecord> {

    private static final long serialVersionUID = -412816059;

    /**
     * The reference instance of <code>information_schema.INNODB_CMP_RESET</code>
     */
    public static final InnodbCmpReset INNODB_CMP_RESET = new InnodbCmpReset();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InnodbCmpResetRecord> getRecordType() {
        return InnodbCmpResetRecord.class;
    }

    /**
     * The column <code>information_schema.INNODB_CMP_RESET.page_size</code>.
     */
    public final TableField<InnodbCmpResetRecord, Integer> PAGE_SIZE = createField("page_size", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>information_schema.INNODB_CMP_RESET.compress_ops</code>.
     */
    public final TableField<InnodbCmpResetRecord, Integer> COMPRESS_OPS = createField("compress_ops", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>information_schema.INNODB_CMP_RESET.compress_ops_ok</code>.
     */
    public final TableField<InnodbCmpResetRecord, Integer> COMPRESS_OPS_OK = createField("compress_ops_ok", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>information_schema.INNODB_CMP_RESET.compress_time</code>.
     */
    public final TableField<InnodbCmpResetRecord, Integer> COMPRESS_TIME = createField("compress_time", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>information_schema.INNODB_CMP_RESET.uncompress_ops</code>.
     */
    public final TableField<InnodbCmpResetRecord, Integer> UNCOMPRESS_OPS = createField("uncompress_ops", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>information_schema.INNODB_CMP_RESET.uncompress_time</code>.
     */
    public final TableField<InnodbCmpResetRecord, Integer> UNCOMPRESS_TIME = createField("uncompress_time", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>information_schema.INNODB_CMP_RESET</code> table reference
     */
    public InnodbCmpReset() {
        this(DSL.name("INNODB_CMP_RESET"), null);
    }

    /**
     * Create an aliased <code>information_schema.INNODB_CMP_RESET</code> table reference
     */
    public InnodbCmpReset(String alias) {
        this(DSL.name(alias), INNODB_CMP_RESET);
    }

    /**
     * Create an aliased <code>information_schema.INNODB_CMP_RESET</code> table reference
     */
    public InnodbCmpReset(Name alias) {
        this(alias, INNODB_CMP_RESET);
    }

    private InnodbCmpReset(Name alias, Table<InnodbCmpResetRecord> aliased) {
        this(alias, aliased, null);
    }

    private InnodbCmpReset(Name alias, Table<InnodbCmpResetRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return InformationSchema.INFORMATION_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InnodbCmpReset as(String alias) {
        return new InnodbCmpReset(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InnodbCmpReset as(Name alias) {
        return new InnodbCmpReset(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public InnodbCmpReset rename(String name) {
        return new InnodbCmpReset(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public InnodbCmpReset rename(Name name) {
        return new InnodbCmpReset(name, null);
    }
}
