/*
 * This file is generated by jOOQ.
*/
package com.anzoo_anzoom.database.information_schema.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InnodbMutexes implements Serializable {

    private static final long serialVersionUID = -1331092114;

    private String   name;
    private String   createFile;
    private UInteger createLine;
    private ULong    osWaits;

    public InnodbMutexes() {}

    public InnodbMutexes(InnodbMutexes value) {
        this.name = value.name;
        this.createFile = value.createFile;
        this.createLine = value.createLine;
        this.osWaits = value.osWaits;
    }

    public InnodbMutexes(
        String   name,
        String   createFile,
        UInteger createLine,
        ULong    osWaits
    ) {
        this.name = name;
        this.createFile = createFile;
        this.createLine = createLine;
        this.osWaits = osWaits;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCreateFile() {
        return this.createFile;
    }

    public void setCreateFile(String createFile) {
        this.createFile = createFile;
    }

    public UInteger getCreateLine() {
        return this.createLine;
    }

    public void setCreateLine(UInteger createLine) {
        this.createLine = createLine;
    }

    public ULong getOsWaits() {
        return this.osWaits;
    }

    public void setOsWaits(ULong osWaits) {
        this.osWaits = osWaits;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InnodbMutexes (");

        sb.append(name);
        sb.append(", ").append(createFile);
        sb.append(", ").append(createLine);
        sb.append(", ").append(osWaits);

        sb.append(")");
        return sb.toString();
    }
}
