/*
 * This file is generated by jOOQ.
*/
package com.anzoo_anzoom.database.anzoo_anzoom;


import com.anzoo_anzoom.database.DefaultCatalog;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.AnjuTags;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.AuthenticationAccessTokens;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.Comments;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.Posts;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.UserContactInfoTypes;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.UserContactInfos;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.UserContactLogs;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.UserContactSubjects;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.UserPasswordEncryptionTypes;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.UserPasswordHistories;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.Users;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AnzooAnzoom extends SchemaImpl {

    private static final long serialVersionUID = -785527544;

    /**
     * The reference instance of <code>anzoo_anzoom</code>
     */
    public static final AnzooAnzoom ANZOO_ANZOOM = new AnzooAnzoom();

    /**
     * The table <code>anzoo_anzoom.anju_tags</code>.
     */
    public final AnjuTags ANJU_TAGS = com.anzoo_anzoom.database.anzoo_anzoom.tables.AnjuTags.ANJU_TAGS;

    /**
     * The table <code>anzoo_anzoom.authentication_access_tokens</code>.
     */
    public final AuthenticationAccessTokens AUTHENTICATION_ACCESS_TOKENS = com.anzoo_anzoom.database.anzoo_anzoom.tables.AuthenticationAccessTokens.AUTHENTICATION_ACCESS_TOKENS;

    /**
     * The table <code>anzoo_anzoom.comments</code>.
     */
    public final Comments COMMENTS = com.anzoo_anzoom.database.anzoo_anzoom.tables.Comments.COMMENTS;

    /**
     * The table <code>anzoo_anzoom.posts</code>.
     */
    public final Posts POSTS = com.anzoo_anzoom.database.anzoo_anzoom.tables.Posts.POSTS;

    /**
     * The table <code>anzoo_anzoom.users</code>.
     */
    public final Users USERS = com.anzoo_anzoom.database.anzoo_anzoom.tables.Users.USERS;

    /**
     * The table <code>anzoo_anzoom.user_contact_infos</code>.
     */
    public final UserContactInfos USER_CONTACT_INFOS = com.anzoo_anzoom.database.anzoo_anzoom.tables.UserContactInfos.USER_CONTACT_INFOS;

    /**
     * The table <code>anzoo_anzoom.user_contact_info_types</code>.
     */
    public final UserContactInfoTypes USER_CONTACT_INFO_TYPES = com.anzoo_anzoom.database.anzoo_anzoom.tables.UserContactInfoTypes.USER_CONTACT_INFO_TYPES;

    /**
     * The table <code>anzoo_anzoom.user_contact_logs</code>.
     */
    public final UserContactLogs USER_CONTACT_LOGS = com.anzoo_anzoom.database.anzoo_anzoom.tables.UserContactLogs.USER_CONTACT_LOGS;

    /**
     * The table <code>anzoo_anzoom.user_contact_subjects</code>.
     */
    public final UserContactSubjects USER_CONTACT_SUBJECTS = com.anzoo_anzoom.database.anzoo_anzoom.tables.UserContactSubjects.USER_CONTACT_SUBJECTS;

    /**
     * The table <code>anzoo_anzoom.user_password_encryption_types</code>.
     */
    public final UserPasswordEncryptionTypes USER_PASSWORD_ENCRYPTION_TYPES = com.anzoo_anzoom.database.anzoo_anzoom.tables.UserPasswordEncryptionTypes.USER_PASSWORD_ENCRYPTION_TYPES;

    /**
     * The table <code>anzoo_anzoom.user_password_histories</code>.
     */
    public final UserPasswordHistories USER_PASSWORD_HISTORIES = com.anzoo_anzoom.database.anzoo_anzoom.tables.UserPasswordHistories.USER_PASSWORD_HISTORIES;

    /**
     * No further instances allowed
     */
    private AnzooAnzoom() {
        super("anzoo_anzoom", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            AnjuTags.ANJU_TAGS,
            AuthenticationAccessTokens.AUTHENTICATION_ACCESS_TOKENS,
            Comments.COMMENTS,
            Posts.POSTS,
            Users.USERS,
            UserContactInfos.USER_CONTACT_INFOS,
            UserContactInfoTypes.USER_CONTACT_INFO_TYPES,
            UserContactLogs.USER_CONTACT_LOGS,
            UserContactSubjects.USER_CONTACT_SUBJECTS,
            UserPasswordEncryptionTypes.USER_PASSWORD_ENCRYPTION_TYPES,
            UserPasswordHistories.USER_PASSWORD_HISTORIES);
    }
}
