/*
 * This file is generated by jOOQ.
*/
package com.anzoo_anzoom.database.anzoo_anzoom;


import com.anzoo_anzoom.database.anzoo_anzoom.tables.AnjuTags;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.AuthenticationAccessTokens;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.Comments;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.Posts;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.UserContactInfoTypes;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.UserContactInfos;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.UserContactLogs;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.UserContactSubjects;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.UserPasswordEncryptionTypes;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.UserPasswordHistories;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.Users;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling indexes of tables of the <code>anzoo_anzoom</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ANJU_TAGS_ANJU_TAGS_TAG_UINDEX = Indexes0.ANJU_TAGS_ANJU_TAGS_TAG_UINDEX;
    public static final Index ANJU_TAGS_PRIMARY = Indexes0.ANJU_TAGS_PRIMARY;
    public static final Index AUTHENTICATION_ACCESS_TOKENS_AUTHENTICATION_ACCESS_TOKENS_AUTH_ID_ACCESS_TOKEN_UINDEX = Indexes0.AUTHENTICATION_ACCESS_TOKENS_AUTHENTICATION_ACCESS_TOKENS_AUTH_ID_ACCESS_TOKEN_UINDEX;
    public static final Index AUTHENTICATION_ACCESS_TOKENS_PRIMARY = Indexes0.AUTHENTICATION_ACCESS_TOKENS_PRIMARY;
    public static final Index COMMENTS_COMMENTS_POSTS_ID_FK = Indexes0.COMMENTS_COMMENTS_POSTS_ID_FK;
    public static final Index COMMENTS_COMMENTS_USERS_ID_FK = Indexes0.COMMENTS_COMMENTS_USERS_ID_FK;
    public static final Index COMMENTS_PRIMARY = Indexes0.COMMENTS_PRIMARY;
    public static final Index POSTS_POSTS_USERS_ID_FK = Indexes0.POSTS_POSTS_USERS_ID_FK;
    public static final Index POSTS_PRIMARY = Indexes0.POSTS_PRIMARY;
    public static final Index USERS_PRIMARY = Indexes0.USERS_PRIMARY;
    public static final Index USERS_USERS_AUTH_ID_UINDEX = Indexes0.USERS_USERS_AUTH_ID_UINDEX;
    public static final Index USERS_USERS_USER_PASSWORD_ENCRYPTION_TYPES_ID_FK = Indexes0.USERS_USERS_USER_PASSWORD_ENCRYPTION_TYPES_ID_FK;
    public static final Index USER_CONTACT_INFOS_PRIMARY = Indexes0.USER_CONTACT_INFOS_PRIMARY;
    public static final Index USER_CONTACT_INFOS_USER_CONTACT_INFOS_USER_CONTACT_INFO_TYPES_ID_FK = Indexes0.USER_CONTACT_INFOS_USER_CONTACT_INFOS_USER_CONTACT_INFO_TYPES_ID_FK;
    public static final Index USER_CONTACT_INFOS_USER_CONTACT_INFOS_USER_ID_TYPE_ID_UINDEX = Indexes0.USER_CONTACT_INFOS_USER_CONTACT_INFOS_USER_ID_TYPE_ID_UINDEX;
    public static final Index USER_CONTACT_INFO_TYPES_PRIMARY = Indexes0.USER_CONTACT_INFO_TYPES_PRIMARY;
    public static final Index USER_CONTACT_INFO_TYPES_USER_CONTACT_INFO_TYPES_TYPE_NAME_UINDEX = Indexes0.USER_CONTACT_INFO_TYPES_USER_CONTACT_INFO_TYPES_TYPE_NAME_UINDEX;
    public static final Index USER_CONTACT_LOGS_PRIMARY = Indexes0.USER_CONTACT_LOGS_PRIMARY;
    public static final Index USER_CONTACT_LOGS_USER_CONTACT_LOGS_USER_CONTACT_INFOS_ID_FK = Indexes0.USER_CONTACT_LOGS_USER_CONTACT_LOGS_USER_CONTACT_INFOS_ID_FK;
    public static final Index USER_CONTACT_LOGS_USER_CONTACT_LOGS_USER_CONTACT_SUBJECTS_ID_FK = Indexes0.USER_CONTACT_LOGS_USER_CONTACT_LOGS_USER_CONTACT_SUBJECTS_ID_FK;
    public static final Index USER_CONTACT_SUBJECTS_PRIMARY = Indexes0.USER_CONTACT_SUBJECTS_PRIMARY;
    public static final Index USER_CONTACT_SUBJECTS_USER_CONTACT_SUBJECTS_TITLE_UINDEX = Indexes0.USER_CONTACT_SUBJECTS_USER_CONTACT_SUBJECTS_TITLE_UINDEX;
    public static final Index USER_PASSWORD_ENCRYPTION_TYPES_PRIMARY = Indexes0.USER_PASSWORD_ENCRYPTION_TYPES_PRIMARY;
    public static final Index USER_PASSWORD_ENCRYPTION_TYPES_USER_PASSWORD_ENCRYPTION_TYPES_TYPE_NAME_SECRET_KEY_UINDEX = Indexes0.USER_PASSWORD_ENCRYPTION_TYPES_USER_PASSWORD_ENCRYPTION_TYPES_TYPE_NAME_SECRET_KEY_UINDEX;
    public static final Index USER_PASSWORD_HISTORIES_PRIMARY = Indexes0.USER_PASSWORD_HISTORIES_PRIMARY;
    public static final Index USER_PASSWORD_HISTORIES_USER_PASSWORD_HISTORIES_USERS_ID_FK = Indexes0.USER_PASSWORD_HISTORIES_USER_PASSWORD_HISTORIES_USERS_ID_FK;
    public static final Index USER_PASSWORD_HISTORIES_USER_PASSWORD_HISTORIES_USER_PASSWORD_ENCRYPTION_TYPES_ID_FK = Indexes0.USER_PASSWORD_HISTORIES_USER_PASSWORD_HISTORIES_USER_PASSWORD_ENCRYPTION_TYPES_ID_FK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index ANJU_TAGS_ANJU_TAGS_TAG_UINDEX = createIndex("anju_tags_tag_uindex", AnjuTags.ANJU_TAGS, new OrderField[] { AnjuTags.ANJU_TAGS.TAG }, true);
        public static Index ANJU_TAGS_PRIMARY = createIndex("PRIMARY", AnjuTags.ANJU_TAGS, new OrderField[] { AnjuTags.ANJU_TAGS.ID }, true);
        public static Index AUTHENTICATION_ACCESS_TOKENS_AUTHENTICATION_ACCESS_TOKENS_AUTH_ID_ACCESS_TOKEN_UINDEX = createIndex("authentication_access_tokens_auth_id_access_token_uindex", AuthenticationAccessTokens.AUTHENTICATION_ACCESS_TOKENS, new OrderField[] { AuthenticationAccessTokens.AUTHENTICATION_ACCESS_TOKENS.USER_ID, AuthenticationAccessTokens.AUTHENTICATION_ACCESS_TOKENS.ACCESS_TOKEN }, true);
        public static Index AUTHENTICATION_ACCESS_TOKENS_PRIMARY = createIndex("PRIMARY", AuthenticationAccessTokens.AUTHENTICATION_ACCESS_TOKENS, new OrderField[] { AuthenticationAccessTokens.AUTHENTICATION_ACCESS_TOKENS.ID }, true);
        public static Index COMMENTS_COMMENTS_POSTS_ID_FK = createIndex("comments_posts_id_fk", Comments.COMMENTS, new OrderField[] { Comments.COMMENTS.POST_ID }, false);
        public static Index COMMENTS_COMMENTS_USERS_ID_FK = createIndex("comments_users_id_fk", Comments.COMMENTS, new OrderField[] { Comments.COMMENTS.USER_ID }, false);
        public static Index COMMENTS_PRIMARY = createIndex("PRIMARY", Comments.COMMENTS, new OrderField[] { Comments.COMMENTS.ID }, true);
        public static Index POSTS_POSTS_USERS_ID_FK = createIndex("posts_users_id_fk", Posts.POSTS, new OrderField[] { Posts.POSTS.USER_ID }, false);
        public static Index POSTS_PRIMARY = createIndex("PRIMARY", Posts.POSTS, new OrderField[] { Posts.POSTS.ID }, true);
        public static Index USERS_PRIMARY = createIndex("PRIMARY", Users.USERS, new OrderField[] { Users.USERS.ID }, true);
        public static Index USERS_USERS_AUTH_ID_UINDEX = createIndex("users_auth_id_uindex", Users.USERS, new OrderField[] { Users.USERS.AUTH_ID }, true);
        public static Index USERS_USERS_USER_PASSWORD_ENCRYPTION_TYPES_ID_FK = createIndex("users_user_password_encryption_types_id_fk", Users.USERS, new OrderField[] { Users.USERS.PASSWORD_ENCRYPTION_TYPE_ID }, false);
        public static Index USER_CONTACT_INFOS_PRIMARY = createIndex("PRIMARY", UserContactInfos.USER_CONTACT_INFOS, new OrderField[] { UserContactInfos.USER_CONTACT_INFOS.ID }, true);
        public static Index USER_CONTACT_INFOS_USER_CONTACT_INFOS_USER_CONTACT_INFO_TYPES_ID_FK = createIndex("user_contact_infos_user_contact_info_types_id_fk", UserContactInfos.USER_CONTACT_INFOS, new OrderField[] { UserContactInfos.USER_CONTACT_INFOS.TYPE_ID }, false);
        public static Index USER_CONTACT_INFOS_USER_CONTACT_INFOS_USER_ID_TYPE_ID_UINDEX = createIndex("user_contact_infos_user_id_type_id_uindex", UserContactInfos.USER_CONTACT_INFOS, new OrderField[] { UserContactInfos.USER_CONTACT_INFOS.USER_ID, UserContactInfos.USER_CONTACT_INFOS.TYPE_ID }, true);
        public static Index USER_CONTACT_INFO_TYPES_PRIMARY = createIndex("PRIMARY", UserContactInfoTypes.USER_CONTACT_INFO_TYPES, new OrderField[] { UserContactInfoTypes.USER_CONTACT_INFO_TYPES.ID }, true);
        public static Index USER_CONTACT_INFO_TYPES_USER_CONTACT_INFO_TYPES_TYPE_NAME_UINDEX = createIndex("user_contact_info_types_type_name_uindex", UserContactInfoTypes.USER_CONTACT_INFO_TYPES, new OrderField[] { UserContactInfoTypes.USER_CONTACT_INFO_TYPES.TYPE_NAME }, true);
        public static Index USER_CONTACT_LOGS_PRIMARY = createIndex("PRIMARY", UserContactLogs.USER_CONTACT_LOGS, new OrderField[] { UserContactLogs.USER_CONTACT_LOGS.ID }, true);
        public static Index USER_CONTACT_LOGS_USER_CONTACT_LOGS_USER_CONTACT_INFOS_ID_FK = createIndex("user_contact_logs_user_contact_infos_id_fk", UserContactLogs.USER_CONTACT_LOGS, new OrderField[] { UserContactLogs.USER_CONTACT_LOGS.INFO_ID }, false);
        public static Index USER_CONTACT_LOGS_USER_CONTACT_LOGS_USER_CONTACT_SUBJECTS_ID_FK = createIndex("user_contact_logs_user_contact_subjects_id_fk", UserContactLogs.USER_CONTACT_LOGS, new OrderField[] { UserContactLogs.USER_CONTACT_LOGS.SUBJECT_ID }, false);
        public static Index USER_CONTACT_SUBJECTS_PRIMARY = createIndex("PRIMARY", UserContactSubjects.USER_CONTACT_SUBJECTS, new OrderField[] { UserContactSubjects.USER_CONTACT_SUBJECTS.ID }, true);
        public static Index USER_CONTACT_SUBJECTS_USER_CONTACT_SUBJECTS_TITLE_UINDEX = createIndex("user_contact_subjects_title_uindex", UserContactSubjects.USER_CONTACT_SUBJECTS, new OrderField[] { UserContactSubjects.USER_CONTACT_SUBJECTS.TITLE }, true);
        public static Index USER_PASSWORD_ENCRYPTION_TYPES_PRIMARY = createIndex("PRIMARY", UserPasswordEncryptionTypes.USER_PASSWORD_ENCRYPTION_TYPES, new OrderField[] { UserPasswordEncryptionTypes.USER_PASSWORD_ENCRYPTION_TYPES.ID }, true);
        public static Index USER_PASSWORD_ENCRYPTION_TYPES_USER_PASSWORD_ENCRYPTION_TYPES_TYPE_NAME_SECRET_KEY_UINDEX = createIndex("user_password_encryption_types_type_name_secret_key_uindex", UserPasswordEncryptionTypes.USER_PASSWORD_ENCRYPTION_TYPES, new OrderField[] { UserPasswordEncryptionTypes.USER_PASSWORD_ENCRYPTION_TYPES.TYPE_NAME, UserPasswordEncryptionTypes.USER_PASSWORD_ENCRYPTION_TYPES.SECRET_KEY }, true);
        public static Index USER_PASSWORD_HISTORIES_PRIMARY = createIndex("PRIMARY", UserPasswordHistories.USER_PASSWORD_HISTORIES, new OrderField[] { UserPasswordHistories.USER_PASSWORD_HISTORIES.ID }, true);
        public static Index USER_PASSWORD_HISTORIES_USER_PASSWORD_HISTORIES_USERS_ID_FK = createIndex("user_password_histories_users_id_fk", UserPasswordHistories.USER_PASSWORD_HISTORIES, new OrderField[] { UserPasswordHistories.USER_PASSWORD_HISTORIES.USER_ID }, false);
        public static Index USER_PASSWORD_HISTORIES_USER_PASSWORD_HISTORIES_USER_PASSWORD_ENCRYPTION_TYPES_ID_FK = createIndex("user_password_histories_user_password_encryption_types_id_fk", UserPasswordHistories.USER_PASSWORD_HISTORIES, new OrderField[] { UserPasswordHistories.USER_PASSWORD_HISTORIES.ENCRYPTION_TYPE_ID }, false);
    }
}
