/*
 * This file is generated by jOOQ.
*/
package com.anzoo_anzoom.database.anzoo_anzoom;


import com.anzoo_anzoom.database.anzoo_anzoom.tables.AnjuTags;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.AuthenticationAccessTokens;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.Comments;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.Posts;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.UserContactInfoTypes;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.UserContactInfos;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.UserContactLogs;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.UserContactSubjects;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.UserPasswordEncryptionTypes;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.UserPasswordHistories;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in anzoo_anzoom
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>anzoo_anzoom.anju_tags</code>.
     */
    public static final AnjuTags ANJU_TAGS = com.anzoo_anzoom.database.anzoo_anzoom.tables.AnjuTags.ANJU_TAGS;

    /**
     * The table <code>anzoo_anzoom.authentication_access_tokens</code>.
     */
    public static final AuthenticationAccessTokens AUTHENTICATION_ACCESS_TOKENS = com.anzoo_anzoom.database.anzoo_anzoom.tables.AuthenticationAccessTokens.AUTHENTICATION_ACCESS_TOKENS;

    /**
     * The table <code>anzoo_anzoom.comments</code>.
     */
    public static final Comments COMMENTS = com.anzoo_anzoom.database.anzoo_anzoom.tables.Comments.COMMENTS;

    /**
     * The table <code>anzoo_anzoom.posts</code>.
     */
    public static final Posts POSTS = com.anzoo_anzoom.database.anzoo_anzoom.tables.Posts.POSTS;

    /**
     * The table <code>anzoo_anzoom.users</code>.
     */
    public static final Users USERS = com.anzoo_anzoom.database.anzoo_anzoom.tables.Users.USERS;

    /**
     * The table <code>anzoo_anzoom.user_contact_infos</code>.
     */
    public static final UserContactInfos USER_CONTACT_INFOS = com.anzoo_anzoom.database.anzoo_anzoom.tables.UserContactInfos.USER_CONTACT_INFOS;

    /**
     * The table <code>anzoo_anzoom.user_contact_info_types</code>.
     */
    public static final UserContactInfoTypes USER_CONTACT_INFO_TYPES = com.anzoo_anzoom.database.anzoo_anzoom.tables.UserContactInfoTypes.USER_CONTACT_INFO_TYPES;

    /**
     * The table <code>anzoo_anzoom.user_contact_logs</code>.
     */
    public static final UserContactLogs USER_CONTACT_LOGS = com.anzoo_anzoom.database.anzoo_anzoom.tables.UserContactLogs.USER_CONTACT_LOGS;

    /**
     * The table <code>anzoo_anzoom.user_contact_subjects</code>.
     */
    public static final UserContactSubjects USER_CONTACT_SUBJECTS = com.anzoo_anzoom.database.anzoo_anzoom.tables.UserContactSubjects.USER_CONTACT_SUBJECTS;

    /**
     * The table <code>anzoo_anzoom.user_password_encryption_types</code>.
     */
    public static final UserPasswordEncryptionTypes USER_PASSWORD_ENCRYPTION_TYPES = com.anzoo_anzoom.database.anzoo_anzoom.tables.UserPasswordEncryptionTypes.USER_PASSWORD_ENCRYPTION_TYPES;

    /**
     * The table <code>anzoo_anzoom.user_password_histories</code>.
     */
    public static final UserPasswordHistories USER_PASSWORD_HISTORIES = com.anzoo_anzoom.database.anzoo_anzoom.tables.UserPasswordHistories.USER_PASSWORD_HISTORIES;
}
