/*
 * This file is generated by jOOQ.
*/
package com.anzoo_anzoom.database.anzoo_anzoom.tables.daos;


import com.anzoo_anzoom.database.anzoo_anzoom.tables.AuthenticationAccessTokens;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.records.AuthenticationAccessTokensRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthenticationAccessTokensDao extends DAOImpl<AuthenticationAccessTokensRecord, com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.AuthenticationAccessTokens, Integer> {

    /**
     * Create a new AuthenticationAccessTokensDao without any configuration
     */
    public AuthenticationAccessTokensDao() {
        super(AuthenticationAccessTokens.AUTHENTICATION_ACCESS_TOKENS, com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.AuthenticationAccessTokens.class);
    }

    /**
     * Create a new AuthenticationAccessTokensDao with an attached configuration
     */
    public AuthenticationAccessTokensDao(Configuration configuration) {
        super(AuthenticationAccessTokens.AUTHENTICATION_ACCESS_TOKENS, com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.AuthenticationAccessTokens.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.AuthenticationAccessTokens object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.AuthenticationAccessTokens> fetchById(Integer... values) {
        return fetch(AuthenticationAccessTokens.AUTHENTICATION_ACCESS_TOKENS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.AuthenticationAccessTokens fetchOneById(Integer value) {
        return fetchOne(AuthenticationAccessTokens.AUTHENTICATION_ACCESS_TOKENS.ID, value);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.AuthenticationAccessTokens> fetchByUserId(Integer... values) {
        return fetch(AuthenticationAccessTokens.AUTHENTICATION_ACCESS_TOKENS.USER_ID, values);
    }

    /**
     * Fetch records that have <code>access_token IN (values)</code>
     */
    public List<com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.AuthenticationAccessTokens> fetchByAccessToken(String... values) {
        return fetch(AuthenticationAccessTokens.AUTHENTICATION_ACCESS_TOKENS.ACCESS_TOKEN, values);
    }

    /**
     * Fetch records that have <code>expired_at IN (values)</code>
     */
    public List<com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.AuthenticationAccessTokens> fetchByExpiredAt(Timestamp... values) {
        return fetch(AuthenticationAccessTokens.AUTHENTICATION_ACCESS_TOKENS.EXPIRED_AT, values);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.AuthenticationAccessTokens> fetchByCreatedAt(Timestamp... values) {
        return fetch(AuthenticationAccessTokens.AUTHENTICATION_ACCESS_TOKENS.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>deleted_at IN (values)</code>
     */
    public List<com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.AuthenticationAccessTokens> fetchByDeletedAt(Timestamp... values) {
        return fetch(AuthenticationAccessTokens.AUTHENTICATION_ACCESS_TOKENS.DELETED_AT, values);
    }
}
