/*
 * This file is generated by jOOQ.
*/
package com.anzoo_anzoom.database.anzoo_anzoom.tables.daos;


import com.anzoo_anzoom.database.anzoo_anzoom.tables.UserContactInfoTypes;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.records.UserContactInfoTypesRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserContactInfoTypesDao extends DAOImpl<UserContactInfoTypesRecord, com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactInfoTypes, Integer> {

    /**
     * Create a new UserContactInfoTypesDao without any configuration
     */
    public UserContactInfoTypesDao() {
        super(UserContactInfoTypes.USER_CONTACT_INFO_TYPES, com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactInfoTypes.class);
    }

    /**
     * Create a new UserContactInfoTypesDao with an attached configuration
     */
    public UserContactInfoTypesDao(Configuration configuration) {
        super(UserContactInfoTypes.USER_CONTACT_INFO_TYPES, com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactInfoTypes.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactInfoTypes object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactInfoTypes> fetchById(Integer... values) {
        return fetch(UserContactInfoTypes.USER_CONTACT_INFO_TYPES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactInfoTypes fetchOneById(Integer value) {
        return fetchOne(UserContactInfoTypes.USER_CONTACT_INFO_TYPES.ID, value);
    }

    /**
     * Fetch records that have <code>type_name IN (values)</code>
     */
    public List<com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactInfoTypes> fetchByTypeName(String... values) {
        return fetch(UserContactInfoTypes.USER_CONTACT_INFO_TYPES.TYPE_NAME, values);
    }

    /**
     * Fetch a unique record that has <code>type_name = value</code>
     */
    public com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactInfoTypes fetchOneByTypeName(String value) {
        return fetchOne(UserContactInfoTypes.USER_CONTACT_INFO_TYPES.TYPE_NAME, value);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactInfoTypes> fetchByCreatedAt(Timestamp... values) {
        return fetch(UserContactInfoTypes.USER_CONTACT_INFO_TYPES.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactInfoTypes> fetchByUpdatedAt(Timestamp... values) {
        return fetch(UserContactInfoTypes.USER_CONTACT_INFO_TYPES.UPDATED_AT, values);
    }

    /**
     * Fetch records that have <code>deleted_at IN (values)</code>
     */
    public List<com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactInfoTypes> fetchByDeletedAt(Timestamp... values) {
        return fetch(UserContactInfoTypes.USER_CONTACT_INFO_TYPES.DELETED_AT, values);
    }
}
