/*
 * This file is generated by jOOQ.
*/
package com.anzoo_anzoom.database.anzoo_anzoom.tables.daos;


import com.anzoo_anzoom.database.anzoo_anzoom.tables.Users;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.records.UsersRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersDao extends DAOImpl<UsersRecord, com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.Users, Integer> {

    /**
     * Create a new UsersDao without any configuration
     */
    public UsersDao() {
        super(Users.USERS, com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.Users.class);
    }

    /**
     * Create a new UsersDao with an attached configuration
     */
    public UsersDao(Configuration configuration) {
        super(Users.USERS, com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.Users.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.Users object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.Users> fetchById(Integer... values) {
        return fetch(Users.USERS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.Users fetchOneById(Integer value) {
        return fetchOne(Users.USERS.ID, value);
    }

    /**
     * Fetch records that have <code>full_name IN (values)</code>
     */
    public List<com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.Users> fetchByFullName(String... values) {
        return fetch(Users.USERS.FULL_NAME, values);
    }

    /**
     * Fetch records that have <code>auth_id IN (values)</code>
     */
    public List<com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.Users> fetchByAuthId(String... values) {
        return fetch(Users.USERS.AUTH_ID, values);
    }

    /**
     * Fetch a unique record that has <code>auth_id = value</code>
     */
    public com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.Users fetchOneByAuthId(String value) {
        return fetchOne(Users.USERS.AUTH_ID, value);
    }

    /**
     * Fetch records that have <code>encrypted_password IN (values)</code>
     */
    public List<com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.Users> fetchByEncryptedPassword(byte[]... values) {
        return fetch(Users.USERS.ENCRYPTED_PASSWORD, values);
    }

    /**
     * Fetch records that have <code>password_encryption_type_id IN (values)</code>
     */
    public List<com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.Users> fetchByPasswordEncryptionTypeId(Integer... values) {
        return fetch(Users.USERS.PASSWORD_ENCRYPTION_TYPE_ID, values);
    }
}
