/*
 * This file is generated by jOOQ.
*/
package com.anzoo_anzoom.database.anzoo_anzoom.tables.daos;


import com.anzoo_anzoom.database.anzoo_anzoom.tables.UserContactLogs;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.records.UserContactLogsRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserContactLogsDao extends DAOImpl<UserContactLogsRecord, com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactLogs, Integer> {

    /**
     * Create a new UserContactLogsDao without any configuration
     */
    public UserContactLogsDao() {
        super(UserContactLogs.USER_CONTACT_LOGS, com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactLogs.class);
    }

    /**
     * Create a new UserContactLogsDao with an attached configuration
     */
    public UserContactLogsDao(Configuration configuration) {
        super(UserContactLogs.USER_CONTACT_LOGS, com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactLogs.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactLogs object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactLogs> fetchById(Integer... values) {
        return fetch(UserContactLogs.USER_CONTACT_LOGS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactLogs fetchOneById(Integer value) {
        return fetchOne(UserContactLogs.USER_CONTACT_LOGS.ID, value);
    }

    /**
     * Fetch records that have <code>info_id IN (values)</code>
     */
    public List<com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactLogs> fetchByInfoId(Integer... values) {
        return fetch(UserContactLogs.USER_CONTACT_LOGS.INFO_ID, values);
    }

    /**
     * Fetch records that have <code>issued_at IN (values)</code>
     */
    public List<com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactLogs> fetchByIssuedAt(Timestamp... values) {
        return fetch(UserContactLogs.USER_CONTACT_LOGS.ISSUED_AT, values);
    }

    /**
     * Fetch records that have <code>subject_id IN (values)</code>
     */
    public List<com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactLogs> fetchBySubjectId(Integer... values) {
        return fetch(UserContactLogs.USER_CONTACT_LOGS.SUBJECT_ID, values);
    }

    /**
     * Fetch records that have <code>contacted_at IN (values)</code>
     */
    public List<com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactLogs> fetchByContactedAt(Timestamp... values) {
        return fetch(UserContactLogs.USER_CONTACT_LOGS.CONTACTED_AT, values);
    }

    /**
     * Fetch records that have <code>content IN (values)</code>
     */
    public List<com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactLogs> fetchByContent(String... values) {
        return fetch(UserContactLogs.USER_CONTACT_LOGS.CONTENT, values);
    }

    /**
     * Fetch records that have <code>deleted_at IN (values)</code>
     */
    public List<com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactLogs> fetchByDeletedAt(Timestamp... values) {
        return fetch(UserContactLogs.USER_CONTACT_LOGS.DELETED_AT, values);
    }
}
