/*
 * This file is generated by jOOQ.
*/
package com.anzoo_anzoom.database.anzoo_anzoom.tables.daos;


import com.anzoo_anzoom.database.anzoo_anzoom.tables.UserContactInfos;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.records.UserContactInfosRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserContactInfosDao extends DAOImpl<UserContactInfosRecord, com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactInfos, Integer> {

    /**
     * Create a new UserContactInfosDao without any configuration
     */
    public UserContactInfosDao() {
        super(UserContactInfos.USER_CONTACT_INFOS, com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactInfos.class);
    }

    /**
     * Create a new UserContactInfosDao with an attached configuration
     */
    public UserContactInfosDao(Configuration configuration) {
        super(UserContactInfos.USER_CONTACT_INFOS, com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactInfos.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactInfos object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactInfos> fetchById(Integer... values) {
        return fetch(UserContactInfos.USER_CONTACT_INFOS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactInfos fetchOneById(Integer value) {
        return fetchOne(UserContactInfos.USER_CONTACT_INFOS.ID, value);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactInfos> fetchByUserId(Integer... values) {
        return fetch(UserContactInfos.USER_CONTACT_INFOS.USER_ID, values);
    }

    /**
     * Fetch records that have <code>type_id IN (values)</code>
     */
    public List<com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactInfos> fetchByTypeId(Integer... values) {
        return fetch(UserContactInfos.USER_CONTACT_INFOS.TYPE_ID, values);
    }
}
