/*
 * This file is generated by jOOQ.
*/
package com.anzoo_anzoom.database.anzoo_anzoom.tables.daos;


import com.anzoo_anzoom.database.anzoo_anzoom.tables.UserContactSubjects;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.records.UserContactSubjectsRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserContactSubjectsDao extends DAOImpl<UserContactSubjectsRecord, com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactSubjects, Integer> {

    /**
     * Create a new UserContactSubjectsDao without any configuration
     */
    public UserContactSubjectsDao() {
        super(UserContactSubjects.USER_CONTACT_SUBJECTS, com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactSubjects.class);
    }

    /**
     * Create a new UserContactSubjectsDao with an attached configuration
     */
    public UserContactSubjectsDao(Configuration configuration) {
        super(UserContactSubjects.USER_CONTACT_SUBJECTS, com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactSubjects.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactSubjects object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactSubjects> fetchById(Integer... values) {
        return fetch(UserContactSubjects.USER_CONTACT_SUBJECTS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactSubjects fetchOneById(Integer value) {
        return fetchOne(UserContactSubjects.USER_CONTACT_SUBJECTS.ID, value);
    }

    /**
     * Fetch records that have <code>title IN (values)</code>
     */
    public List<com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactSubjects> fetchByTitle(String... values) {
        return fetch(UserContactSubjects.USER_CONTACT_SUBJECTS.TITLE, values);
    }

    /**
     * Fetch a unique record that has <code>title = value</code>
     */
    public com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactSubjects fetchOneByTitle(String value) {
        return fetchOne(UserContactSubjects.USER_CONTACT_SUBJECTS.TITLE, value);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactSubjects> fetchByCreatedAt(Timestamp... values) {
        return fetch(UserContactSubjects.USER_CONTACT_SUBJECTS.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactSubjects> fetchByUpdatedAt(Timestamp... values) {
        return fetch(UserContactSubjects.USER_CONTACT_SUBJECTS.UPDATED_AT, values);
    }

    /**
     * Fetch records that have <code>deleted_at IN (values)</code>
     */
    public List<com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserContactSubjects> fetchByDeletedAt(Timestamp... values) {
        return fetch(UserContactSubjects.USER_CONTACT_SUBJECTS.DELETED_AT, values);
    }
}
