/*
 * This file is generated by jOOQ.
*/
package com.anzoo_anzoom.database.anzoo_anzoom.tables.daos;


import com.anzoo_anzoom.database.anzoo_anzoom.tables.UserPasswordHistories;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.records.UserPasswordHistoriesRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserPasswordHistoriesDao extends DAOImpl<UserPasswordHistoriesRecord, com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserPasswordHistories, Integer> {

    /**
     * Create a new UserPasswordHistoriesDao without any configuration
     */
    public UserPasswordHistoriesDao() {
        super(UserPasswordHistories.USER_PASSWORD_HISTORIES, com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserPasswordHistories.class);
    }

    /**
     * Create a new UserPasswordHistoriesDao with an attached configuration
     */
    public UserPasswordHistoriesDao(Configuration configuration) {
        super(UserPasswordHistories.USER_PASSWORD_HISTORIES, com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserPasswordHistories.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserPasswordHistories object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserPasswordHistories> fetchById(Integer... values) {
        return fetch(UserPasswordHistories.USER_PASSWORD_HISTORIES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserPasswordHistories fetchOneById(Integer value) {
        return fetchOne(UserPasswordHistories.USER_PASSWORD_HISTORIES.ID, value);
    }

    /**
     * Fetch records that have <code>encrypted_password IN (values)</code>
     */
    public List<com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserPasswordHistories> fetchByEncryptedPassword(byte[]... values) {
        return fetch(UserPasswordHistories.USER_PASSWORD_HISTORIES.ENCRYPTED_PASSWORD, values);
    }

    /**
     * Fetch records that have <code>encryption_type_id IN (values)</code>
     */
    public List<com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserPasswordHistories> fetchByEncryptionTypeId(Integer... values) {
        return fetch(UserPasswordHistories.USER_PASSWORD_HISTORIES.ENCRYPTION_TYPE_ID, values);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserPasswordHistories> fetchByUserId(Integer... values) {
        return fetch(UserPasswordHistories.USER_PASSWORD_HISTORIES.USER_ID, values);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.anzoo_anzoom.database.anzoo_anzoom.tables.pojos.UserPasswordHistories> fetchByCreatedAt(Timestamp... values) {
        return fetch(UserPasswordHistories.USER_PASSWORD_HISTORIES.CREATED_AT, values);
    }
}
