/*
 * This file is generated by jOOQ.
*/
package com.anzoo_anzoom.database.anzoo_anzoom.tables;


import com.anzoo_anzoom.database.anzoo_anzoom.AnzooAnzoom;
import com.anzoo_anzoom.database.anzoo_anzoom.Indexes;
import com.anzoo_anzoom.database.anzoo_anzoom.Keys;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.records.UserPasswordHistoriesRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserPasswordHistories extends TableImpl<UserPasswordHistoriesRecord> {

    private static final long serialVersionUID = -1693681572;

    /**
     * The reference instance of <code>anzoo_anzoom.user_password_histories</code>
     */
    public static final UserPasswordHistories USER_PASSWORD_HISTORIES = new UserPasswordHistories();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserPasswordHistoriesRecord> getRecordType() {
        return UserPasswordHistoriesRecord.class;
    }

    /**
     * The column <code>anzoo_anzoom.user_password_histories.id</code>.
     */
    public final TableField<UserPasswordHistoriesRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>anzoo_anzoom.user_password_histories.encrypted_password</code>.
     */
    public final TableField<UserPasswordHistoriesRecord, byte[]> ENCRYPTED_PASSWORD = createField("encrypted_password", org.jooq.impl.SQLDataType.BINARY(64).nullable(false), this, "");

    /**
     * The column <code>anzoo_anzoom.user_password_histories.encryption_type_id</code>.
     */
    public final TableField<UserPasswordHistoriesRecord, Integer> ENCRYPTION_TYPE_ID = createField("encryption_type_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>anzoo_anzoom.user_password_histories.user_id</code>.
     */
    public final TableField<UserPasswordHistoriesRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>anzoo_anzoom.user_password_histories.created_at</code>.
     */
    public final TableField<UserPasswordHistoriesRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("current_timestamp()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>anzoo_anzoom.user_password_histories</code> table reference
     */
    public UserPasswordHistories() {
        this(DSL.name("user_password_histories"), null);
    }

    /**
     * Create an aliased <code>anzoo_anzoom.user_password_histories</code> table reference
     */
    public UserPasswordHistories(String alias) {
        this(DSL.name(alias), USER_PASSWORD_HISTORIES);
    }

    /**
     * Create an aliased <code>anzoo_anzoom.user_password_histories</code> table reference
     */
    public UserPasswordHistories(Name alias) {
        this(alias, USER_PASSWORD_HISTORIES);
    }

    private UserPasswordHistories(Name alias, Table<UserPasswordHistoriesRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserPasswordHistories(Name alias, Table<UserPasswordHistoriesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return AnzooAnzoom.ANZOO_ANZOOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.USER_PASSWORD_HISTORIES_PRIMARY, Indexes.USER_PASSWORD_HISTORIES_USER_PASSWORD_HISTORIES_USERS_ID_FK, Indexes.USER_PASSWORD_HISTORIES_USER_PASSWORD_HISTORIES_USER_PASSWORD_ENCRYPTION_TYPES_ID_FK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<UserPasswordHistoriesRecord, Integer> getIdentity() {
        return Keys.IDENTITY_USER_PASSWORD_HISTORIES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UserPasswordHistoriesRecord> getPrimaryKey() {
        return Keys.KEY_USER_PASSWORD_HISTORIES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UserPasswordHistoriesRecord>> getKeys() {
        return Arrays.<UniqueKey<UserPasswordHistoriesRecord>>asList(Keys.KEY_USER_PASSWORD_HISTORIES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<UserPasswordHistoriesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<UserPasswordHistoriesRecord, ?>>asList(Keys.USER_PASSWORD_HISTORIES_USER_PASSWORD_ENCRYPTION_TYPES_ID_FK, Keys.USER_PASSWORD_HISTORIES_USERS_ID_FK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPasswordHistories as(String alias) {
        return new UserPasswordHistories(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPasswordHistories as(Name alias) {
        return new UserPasswordHistories(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserPasswordHistories rename(String name) {
        return new UserPasswordHistories(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserPasswordHistories rename(Name name) {
        return new UserPasswordHistories(name, null);
    }
}
