/*
 * This file is generated by jOOQ.
*/
package com.anzoo_anzoom.database.anzoo_anzoom.tables;


import com.anzoo_anzoom.database.anzoo_anzoom.AnzooAnzoom;
import com.anzoo_anzoom.database.anzoo_anzoom.Indexes;
import com.anzoo_anzoom.database.anzoo_anzoom.Keys;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.records.UserContactLogsRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserContactLogs extends TableImpl<UserContactLogsRecord> {

    private static final long serialVersionUID = 406288694;

    /**
     * The reference instance of <code>anzoo_anzoom.user_contact_logs</code>
     */
    public static final UserContactLogs USER_CONTACT_LOGS = new UserContactLogs();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserContactLogsRecord> getRecordType() {
        return UserContactLogsRecord.class;
    }

    /**
     * The column <code>anzoo_anzoom.user_contact_logs.id</code>.
     */
    public final TableField<UserContactLogsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>anzoo_anzoom.user_contact_logs.info_id</code>.
     */
    public final TableField<UserContactLogsRecord, Integer> INFO_ID = createField("info_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>anzoo_anzoom.user_contact_logs.issued_at</code>.
     */
    public final TableField<UserContactLogsRecord, Timestamp> ISSUED_AT = createField("issued_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("current_timestamp()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>anzoo_anzoom.user_contact_logs.subject_id</code>.
     */
    public final TableField<UserContactLogsRecord, Integer> SUBJECT_ID = createField("subject_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>anzoo_anzoom.user_contact_logs.contacted_at</code>.
     */
    public final TableField<UserContactLogsRecord, Timestamp> CONTACTED_AT = createField("contacted_at", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>anzoo_anzoom.user_contact_logs.content</code>.
     */
    public final TableField<UserContactLogsRecord, String> CONTENT = createField("content", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>anzoo_anzoom.user_contact_logs.deleted_at</code>.
     */
    public final TableField<UserContactLogsRecord, Timestamp> DELETED_AT = createField("deleted_at", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>anzoo_anzoom.user_contact_logs</code> table reference
     */
    public UserContactLogs() {
        this(DSL.name("user_contact_logs"), null);
    }

    /**
     * Create an aliased <code>anzoo_anzoom.user_contact_logs</code> table reference
     */
    public UserContactLogs(String alias) {
        this(DSL.name(alias), USER_CONTACT_LOGS);
    }

    /**
     * Create an aliased <code>anzoo_anzoom.user_contact_logs</code> table reference
     */
    public UserContactLogs(Name alias) {
        this(alias, USER_CONTACT_LOGS);
    }

    private UserContactLogs(Name alias, Table<UserContactLogsRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserContactLogs(Name alias, Table<UserContactLogsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return AnzooAnzoom.ANZOO_ANZOOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.USER_CONTACT_LOGS_PRIMARY, Indexes.USER_CONTACT_LOGS_USER_CONTACT_LOGS_USER_CONTACT_INFOS_ID_FK, Indexes.USER_CONTACT_LOGS_USER_CONTACT_LOGS_USER_CONTACT_SUBJECTS_ID_FK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<UserContactLogsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_USER_CONTACT_LOGS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UserContactLogsRecord> getPrimaryKey() {
        return Keys.KEY_USER_CONTACT_LOGS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UserContactLogsRecord>> getKeys() {
        return Arrays.<UniqueKey<UserContactLogsRecord>>asList(Keys.KEY_USER_CONTACT_LOGS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<UserContactLogsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<UserContactLogsRecord, ?>>asList(Keys.USER_CONTACT_LOGS_USER_CONTACT_INFOS_ID_FK, Keys.USER_CONTACT_LOGS_USER_CONTACT_SUBJECTS_ID_FK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserContactLogs as(String alias) {
        return new UserContactLogs(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserContactLogs as(Name alias) {
        return new UserContactLogs(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserContactLogs rename(String name) {
        return new UserContactLogs(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserContactLogs rename(Name name) {
        return new UserContactLogs(name, null);
    }
}
