/*
 * This file is generated by jOOQ.
*/
package com.anzoo_anzoom.database.anzoo_anzoom.tables;


import com.anzoo_anzoom.database.anzoo_anzoom.AnzooAnzoom;
import com.anzoo_anzoom.database.anzoo_anzoom.Indexes;
import com.anzoo_anzoom.database.anzoo_anzoom.Keys;
import com.anzoo_anzoom.database.anzoo_anzoom.tables.records.UserContactSubjectsRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserContactSubjects extends TableImpl<UserContactSubjectsRecord> {

    private static final long serialVersionUID = -1295713034;

    /**
     * The reference instance of <code>anzoo_anzoom.user_contact_subjects</code>
     */
    public static final UserContactSubjects USER_CONTACT_SUBJECTS = new UserContactSubjects();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserContactSubjectsRecord> getRecordType() {
        return UserContactSubjectsRecord.class;
    }

    /**
     * The column <code>anzoo_anzoom.user_contact_subjects.id</code>.
     */
    public final TableField<UserContactSubjectsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>anzoo_anzoom.user_contact_subjects.title</code>.
     */
    public final TableField<UserContactSubjectsRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR(1024).nullable(false), this, "");

    /**
     * The column <code>anzoo_anzoom.user_contact_subjects.created_at</code>.
     */
    public final TableField<UserContactSubjectsRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("current_timestamp()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>anzoo_anzoom.user_contact_subjects.updated_at</code>.
     */
    public final TableField<UserContactSubjectsRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>anzoo_anzoom.user_contact_subjects.deleted_at</code>.
     */
    public final TableField<UserContactSubjectsRecord, Timestamp> DELETED_AT = createField("deleted_at", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>anzoo_anzoom.user_contact_subjects</code> table reference
     */
    public UserContactSubjects() {
        this(DSL.name("user_contact_subjects"), null);
    }

    /**
     * Create an aliased <code>anzoo_anzoom.user_contact_subjects</code> table reference
     */
    public UserContactSubjects(String alias) {
        this(DSL.name(alias), USER_CONTACT_SUBJECTS);
    }

    /**
     * Create an aliased <code>anzoo_anzoom.user_contact_subjects</code> table reference
     */
    public UserContactSubjects(Name alias) {
        this(alias, USER_CONTACT_SUBJECTS);
    }

    private UserContactSubjects(Name alias, Table<UserContactSubjectsRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserContactSubjects(Name alias, Table<UserContactSubjectsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return AnzooAnzoom.ANZOO_ANZOOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.USER_CONTACT_SUBJECTS_PRIMARY, Indexes.USER_CONTACT_SUBJECTS_USER_CONTACT_SUBJECTS_TITLE_UINDEX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<UserContactSubjectsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_USER_CONTACT_SUBJECTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UserContactSubjectsRecord> getPrimaryKey() {
        return Keys.KEY_USER_CONTACT_SUBJECTS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UserContactSubjectsRecord>> getKeys() {
        return Arrays.<UniqueKey<UserContactSubjectsRecord>>asList(Keys.KEY_USER_CONTACT_SUBJECTS_PRIMARY, Keys.KEY_USER_CONTACT_SUBJECTS_USER_CONTACT_SUBJECTS_TITLE_UINDEX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserContactSubjects as(String alias) {
        return new UserContactSubjects(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserContactSubjects as(Name alias) {
        return new UserContactSubjects(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserContactSubjects rename(String name) {
        return new UserContactSubjects(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserContactSubjects rename(Name name) {
        return new UserContactSubjects(name, null);
    }
}
