/*
 * This file is generated by jOOQ.
*/
package com.anzoo_anzoom.database.anzoo_anzoom.tables.records;


import com.anzoo_anzoom.database.anzoo_anzoom.tables.AnjuTags;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AnjuTagsRecord extends UpdatableRecordImpl<AnjuTagsRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = -916421489;

    /**
     * Setter for <code>anzoo_anzoom.anju_tags.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>anzoo_anzoom.anju_tags.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>anzoo_anzoom.anju_tags.tag</code>.
     */
    public void setTag(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>anzoo_anzoom.anju_tags.tag</code>.
     */
    public String getTag() {
        return (String) get(1);
    }

    /**
     * Setter for <code>anzoo_anzoom.anju_tags.tag_count</code>.
     */
    public void setTagCount(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>anzoo_anzoom.anju_tags.tag_count</code>.
     */
    public Integer getTagCount() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return AnjuTags.ANJU_TAGS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return AnjuTags.ANJU_TAGS.TAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return AnjuTags.ANJU_TAGS.TAG_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getTagCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getTagCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnjuTagsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnjuTagsRecord value2(String value) {
        setTag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnjuTagsRecord value3(Integer value) {
        setTagCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AnjuTagsRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AnjuTagsRecord
     */
    public AnjuTagsRecord() {
        super(AnjuTags.ANJU_TAGS);
    }

    /**
     * Create a detached, initialised AnjuTagsRecord
     */
    public AnjuTagsRecord(Integer id, String tag, Integer tagCount) {
        super(AnjuTags.ANJU_TAGS);

        set(0, id);
        set(1, tag);
        set(2, tagCount);
    }
}
