/*
 * This file is generated by jOOQ.
*/
package com.anzoo_anzoom.database.anzoo_anzoom.tables.records;


import com.anzoo_anzoom.database.anzoo_anzoom.tables.AuthenticationAccessTokens;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthenticationAccessTokensRecord extends UpdatableRecordImpl<AuthenticationAccessTokensRecord> implements Record6<Integer, Integer, String, Timestamp, Timestamp, Timestamp> {

    private static final long serialVersionUID = -970988806;

    /**
     * Setter for <code>anzoo_anzoom.authentication_access_tokens.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>anzoo_anzoom.authentication_access_tokens.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>anzoo_anzoom.authentication_access_tokens.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>anzoo_anzoom.authentication_access_tokens.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>anzoo_anzoom.authentication_access_tokens.access_token</code>.
     */
    public void setAccessToken(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>anzoo_anzoom.authentication_access_tokens.access_token</code>.
     */
    public String getAccessToken() {
        return (String) get(2);
    }

    /**
     * Setter for <code>anzoo_anzoom.authentication_access_tokens.expired_at</code>.
     */
    public void setExpiredAt(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>anzoo_anzoom.authentication_access_tokens.expired_at</code>.
     */
    public Timestamp getExpiredAt() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>anzoo_anzoom.authentication_access_tokens.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>anzoo_anzoom.authentication_access_tokens.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>anzoo_anzoom.authentication_access_tokens.deleted_at</code>.
     */
    public void setDeletedAt(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>anzoo_anzoom.authentication_access_tokens.deleted_at</code>.
     */
    public Timestamp getDeletedAt() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, String, Timestamp, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, String, Timestamp, Timestamp, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return AuthenticationAccessTokens.AUTHENTICATION_ACCESS_TOKENS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return AuthenticationAccessTokens.AUTHENTICATION_ACCESS_TOKENS.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return AuthenticationAccessTokens.AUTHENTICATION_ACCESS_TOKENS.ACCESS_TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return AuthenticationAccessTokens.AUTHENTICATION_ACCESS_TOKENS.EXPIRED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return AuthenticationAccessTokens.AUTHENTICATION_ACCESS_TOKENS.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return AuthenticationAccessTokens.AUTHENTICATION_ACCESS_TOKENS.DELETED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getAccessToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getExpiredAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAccessToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getExpiredAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthenticationAccessTokensRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthenticationAccessTokensRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthenticationAccessTokensRecord value3(String value) {
        setAccessToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthenticationAccessTokensRecord value4(Timestamp value) {
        setExpiredAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthenticationAccessTokensRecord value5(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthenticationAccessTokensRecord value6(Timestamp value) {
        setDeletedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthenticationAccessTokensRecord values(Integer value1, Integer value2, String value3, Timestamp value4, Timestamp value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthenticationAccessTokensRecord
     */
    public AuthenticationAccessTokensRecord() {
        super(AuthenticationAccessTokens.AUTHENTICATION_ACCESS_TOKENS);
    }

    /**
     * Create a detached, initialised AuthenticationAccessTokensRecord
     */
    public AuthenticationAccessTokensRecord(Integer id, Integer userId, String accessToken, Timestamp expiredAt, Timestamp createdAt, Timestamp deletedAt) {
        super(AuthenticationAccessTokens.AUTHENTICATION_ACCESS_TOKENS);

        set(0, id);
        set(1, userId);
        set(2, accessToken);
        set(3, expiredAt);
        set(4, createdAt);
        set(5, deletedAt);
    }
}
