/*
 * This file is generated by jOOQ.
*/
package com.anzoo_anzoom.database.anzoo_anzoom.tables.records;


import com.anzoo_anzoom.database.anzoo_anzoom.tables.Posts;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostsRecord extends UpdatableRecordImpl<PostsRecord> implements Record10<Integer, Integer, String, String, Integer, Integer, Integer, Timestamp, Timestamp, Timestamp> {

    private static final long serialVersionUID = -337429974;

    /**
     * Setter for <code>anzoo_anzoom.posts.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>anzoo_anzoom.posts.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>anzoo_anzoom.posts.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>anzoo_anzoom.posts.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>anzoo_anzoom.posts.photo_url</code>.
     */
    public void setPhotoUrl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>anzoo_anzoom.posts.photo_url</code>.
     */
    public String getPhotoUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>anzoo_anzoom.posts.content</code>.
     */
    public void setContent(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>anzoo_anzoom.posts.content</code>.
     */
    public String getContent() {
        return (String) get(3);
    }

    /**
     * Setter for <code>anzoo_anzoom.posts.beer_score</code>.
     */
    public void setBeerScore(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>anzoo_anzoom.posts.beer_score</code>.
     */
    public Integer getBeerScore() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>anzoo_anzoom.posts.soju_score</code>.
     */
    public void setSojuScore(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>anzoo_anzoom.posts.soju_score</code>.
     */
    public Integer getSojuScore() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>anzoo_anzoom.posts.traditional_alcoholic_drinks_score</code>.
     */
    public void setTraditionalAlcoholicDrinksScore(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>anzoo_anzoom.posts.traditional_alcoholic_drinks_score</code>.
     */
    public Integer getTraditionalAlcoholicDrinksScore() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>anzoo_anzoom.posts.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>anzoo_anzoom.posts.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>anzoo_anzoom.posts.updated_at</code>.
     */
    public void setUpdatedAt(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>anzoo_anzoom.posts.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>anzoo_anzoom.posts.deleted_at</code>.
     */
    public void setDeletedAt(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>anzoo_anzoom.posts.deleted_at</code>.
     */
    public Timestamp getDeletedAt() {
        return (Timestamp) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, String, String, Integer, Integer, Integer, Timestamp, Timestamp, Timestamp> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, String, String, Integer, Integer, Integer, Timestamp, Timestamp, Timestamp> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Posts.POSTS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Posts.POSTS.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Posts.POSTS.PHOTO_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Posts.POSTS.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Posts.POSTS.BEER_SCORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Posts.POSTS.SOJU_SCORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Posts.POSTS.TRADITIONAL_ALCOHOLIC_DRINKS_SCORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return Posts.POSTS.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return Posts.POSTS.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return Posts.POSTS.DELETED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPhotoUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getBeerScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getSojuScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getTraditionalAlcoholicDrinksScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPhotoUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getBeerScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getSojuScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getTraditionalAlcoholicDrinksScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostsRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostsRecord value3(String value) {
        setPhotoUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostsRecord value4(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostsRecord value5(Integer value) {
        setBeerScore(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostsRecord value6(Integer value) {
        setSojuScore(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostsRecord value7(Integer value) {
        setTraditionalAlcoholicDrinksScore(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostsRecord value8(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostsRecord value9(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostsRecord value10(Timestamp value) {
        setDeletedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostsRecord values(Integer value1, Integer value2, String value3, String value4, Integer value5, Integer value6, Integer value7, Timestamp value8, Timestamp value9, Timestamp value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PostsRecord
     */
    public PostsRecord() {
        super(Posts.POSTS);
    }

    /**
     * Create a detached, initialised PostsRecord
     */
    public PostsRecord(Integer id, Integer userId, String photoUrl, String content, Integer beerScore, Integer sojuScore, Integer traditionalAlcoholicDrinksScore, Timestamp createdAt, Timestamp updatedAt, Timestamp deletedAt) {
        super(Posts.POSTS);

        set(0, id);
        set(1, userId);
        set(2, photoUrl);
        set(3, content);
        set(4, beerScore);
        set(5, sojuScore);
        set(6, traditionalAlcoholicDrinksScore);
        set(7, createdAt);
        set(8, updatedAt);
        set(9, deletedAt);
    }
}
