/*
 * This file is generated by jOOQ.
*/
package com.anzoo_anzoom.database.anzoo_anzoom.tables.records;


import com.anzoo_anzoom.database.anzoo_anzoom.tables.UserContactLogs;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserContactLogsRecord extends UpdatableRecordImpl<UserContactLogsRecord> implements Record7<Integer, Integer, Timestamp, Integer, Timestamp, String, Timestamp> {

    private static final long serialVersionUID = 1527254059;

    /**
     * Setter for <code>anzoo_anzoom.user_contact_logs.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>anzoo_anzoom.user_contact_logs.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>anzoo_anzoom.user_contact_logs.info_id</code>.
     */
    public void setInfoId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>anzoo_anzoom.user_contact_logs.info_id</code>.
     */
    public Integer getInfoId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>anzoo_anzoom.user_contact_logs.issued_at</code>.
     */
    public void setIssuedAt(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>anzoo_anzoom.user_contact_logs.issued_at</code>.
     */
    public Timestamp getIssuedAt() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>anzoo_anzoom.user_contact_logs.subject_id</code>.
     */
    public void setSubjectId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>anzoo_anzoom.user_contact_logs.subject_id</code>.
     */
    public Integer getSubjectId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>anzoo_anzoom.user_contact_logs.contacted_at</code>.
     */
    public void setContactedAt(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>anzoo_anzoom.user_contact_logs.contacted_at</code>.
     */
    public Timestamp getContactedAt() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>anzoo_anzoom.user_contact_logs.content</code>.
     */
    public void setContent(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>anzoo_anzoom.user_contact_logs.content</code>.
     */
    public String getContent() {
        return (String) get(5);
    }

    /**
     * Setter for <code>anzoo_anzoom.user_contact_logs.deleted_at</code>.
     */
    public void setDeletedAt(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>anzoo_anzoom.user_contact_logs.deleted_at</code>.
     */
    public Timestamp getDeletedAt() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Timestamp, Integer, Timestamp, String, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Timestamp, Integer, Timestamp, String, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserContactLogs.USER_CONTACT_LOGS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UserContactLogs.USER_CONTACT_LOGS.INFO_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return UserContactLogs.USER_CONTACT_LOGS.ISSUED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return UserContactLogs.USER_CONTACT_LOGS.SUBJECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return UserContactLogs.USER_CONTACT_LOGS.CONTACTED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return UserContactLogs.USER_CONTACT_LOGS.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return UserContactLogs.USER_CONTACT_LOGS.DELETED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getInfoId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getIssuedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getSubjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getContactedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getInfoId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getIssuedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getSubjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getContactedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserContactLogsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserContactLogsRecord value2(Integer value) {
        setInfoId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserContactLogsRecord value3(Timestamp value) {
        setIssuedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserContactLogsRecord value4(Integer value) {
        setSubjectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserContactLogsRecord value5(Timestamp value) {
        setContactedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserContactLogsRecord value6(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserContactLogsRecord value7(Timestamp value) {
        setDeletedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserContactLogsRecord values(Integer value1, Integer value2, Timestamp value3, Integer value4, Timestamp value5, String value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserContactLogsRecord
     */
    public UserContactLogsRecord() {
        super(UserContactLogs.USER_CONTACT_LOGS);
    }

    /**
     * Create a detached, initialised UserContactLogsRecord
     */
    public UserContactLogsRecord(Integer id, Integer infoId, Timestamp issuedAt, Integer subjectId, Timestamp contactedAt, String content, Timestamp deletedAt) {
        super(UserContactLogs.USER_CONTACT_LOGS);

        set(0, id);
        set(1, infoId);
        set(2, issuedAt);
        set(3, subjectId);
        set(4, contactedAt);
        set(5, content);
        set(6, deletedAt);
    }
}
