/*
 * This file is generated by jOOQ.
*/
package com.anzoo_anzoom.database.anzoo_anzoom.tables.records;


import com.anzoo_anzoom.database.anzoo_anzoom.tables.UserPasswordEncryptionTypes;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserPasswordEncryptionTypesRecord extends UpdatableRecordImpl<UserPasswordEncryptionTypesRecord> implements Record7<Integer, String, byte[], String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -2097716865;

    /**
     * Setter for <code>anzoo_anzoom.user_password_encryption_types.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>anzoo_anzoom.user_password_encryption_types.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>anzoo_anzoom.user_password_encryption_types.type_name</code>.
     */
    public void setTypeName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>anzoo_anzoom.user_password_encryption_types.type_name</code>.
     */
    public String getTypeName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>anzoo_anzoom.user_password_encryption_types.secret_key</code>.
     */
    public void setSecretKey(byte... value) {
        set(2, value);
    }

    /**
     * Getter for <code>anzoo_anzoom.user_password_encryption_types.secret_key</code>.
     */
    public byte[] getSecretKey() {
        return (byte[]) get(2);
    }

    /**
     * Setter for <code>anzoo_anzoom.user_password_encryption_types.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>anzoo_anzoom.user_password_encryption_types.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>anzoo_anzoom.user_password_encryption_types.url</code>.
     */
    public void setUrl(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>anzoo_anzoom.user_password_encryption_types.url</code>.
     */
    public String getUrl() {
        return (String) get(4);
    }

    /**
     * Setter for <code>anzoo_anzoom.user_password_encryption_types.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>anzoo_anzoom.user_password_encryption_types.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>anzoo_anzoom.user_password_encryption_types.deleted_at</code>.
     */
    public void setDeletedAt(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>anzoo_anzoom.user_password_encryption_types.deleted_at</code>.
     */
    public Timestamp getDeletedAt() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, byte[], String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, byte[], String, String, Timestamp, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserPasswordEncryptionTypes.USER_PASSWORD_ENCRYPTION_TYPES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return UserPasswordEncryptionTypes.USER_PASSWORD_ENCRYPTION_TYPES.TYPE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field3() {
        return UserPasswordEncryptionTypes.USER_PASSWORD_ENCRYPTION_TYPES.SECRET_KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return UserPasswordEncryptionTypes.USER_PASSWORD_ENCRYPTION_TYPES.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return UserPasswordEncryptionTypes.USER_PASSWORD_ENCRYPTION_TYPES.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return UserPasswordEncryptionTypes.USER_PASSWORD_ENCRYPTION_TYPES.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return UserPasswordEncryptionTypes.USER_PASSWORD_ENCRYPTION_TYPES.DELETED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTypeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component3() {
        return getSecretKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTypeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value3() {
        return getSecretKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPasswordEncryptionTypesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPasswordEncryptionTypesRecord value2(String value) {
        setTypeName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPasswordEncryptionTypesRecord value3(byte... value) {
        setSecretKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPasswordEncryptionTypesRecord value4(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPasswordEncryptionTypesRecord value5(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPasswordEncryptionTypesRecord value6(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPasswordEncryptionTypesRecord value7(Timestamp value) {
        setDeletedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPasswordEncryptionTypesRecord values(Integer value1, String value2, byte[] value3, String value4, String value5, Timestamp value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserPasswordEncryptionTypesRecord
     */
    public UserPasswordEncryptionTypesRecord() {
        super(UserPasswordEncryptionTypes.USER_PASSWORD_ENCRYPTION_TYPES);
    }

    /**
     * Create a detached, initialised UserPasswordEncryptionTypesRecord
     */
    public UserPasswordEncryptionTypesRecord(Integer id, String typeName, byte[] secretKey, String description, String url, Timestamp createdAt, Timestamp deletedAt) {
        super(UserPasswordEncryptionTypes.USER_PASSWORD_ENCRYPTION_TYPES);

        set(0, id);
        set(1, typeName);
        set(2, secretKey);
        set(3, description);
        set(4, url);
        set(5, createdAt);
        set(6, deletedAt);
    }
}
